version: "3"
services:
    nginx:
        image: nginx
        networks: 
            - pi4-net
    vault:
        image: vault
        cap_add: 
            - IPC_LOCK
        volumes:     
            - vault-data
        networks: 
            - pi4-net

volumes: 
    vault-data:

networks: 
    pi4-net:
