FROM python:3.10

WORKDIR /spleeter

RUN apt-get update && apt-get install -y ffmpeg libsndfile1
RUN pip install spleeter
RUN wget https://github.com/deezer/spleeter/raw/master/audio_example.mp3

CMD bash
