name: ddclient

on:
  push:
    paths:
      - 'ddclient/**'
      - '.github/workflows/ddclient.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: marizmendi/ddclient
          tags: latest
          platform: "linux/arm64"
          context: ddclient
          containerfiles: ./Containerfile
