name: terraform

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: marizmendi/terraform
          tags: latest
          platform: "linux/arm64"
          containerfiles: ./terraform/Containerfile

      - name: Push To ghcr.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: marizmendi/terraform
          tags: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
